import { useState } from 'react';
import { useSignals } from '../../api/market/hooks';
import { PageHeader, Card, CardLabel, Spinner, Empty } from '../../components/ui/index';

const fmt$ = v => v >= 1000 ? `$${(v/1000).toFixed(2)}k` : parseFloat((v||0).toFixed(5));

const SIGNAL_GROUPS = [
  { label: 'FOREX',       syms: 'EURUSD,GBPUSD,USDJPY,AUDUSD,USDCAD,NZDUSD' },
  { label: 'COMMODITIES', syms: 'XAUUSD,XAGUSD,CRUDEOIL,NATGAS,COPPER' },
  { label: 'INDICES',     syms: 'SPX,NDX,DJI,NIFTY50,BANKNIFTY' },
  { label: 'CRYPTO',      syms: 'BTCUSD,ETHUSD,SOLUSD,BNBUSD' },
  { label: 'FUTURES',     syms: 'NQ,ES,YM' },
];

const SignalCard = ({ signal }) => {
  const isLong  = signal.type === 'LONG';
  const accent  = isLong ? '#00ffb3' : '#ff3366';
  const fmt     = v => parseFloat((v||0).toFixed(5));

  return (
    <div className="border p-4 card-glow transition-all" style={{
      background: 'rgba(10,10,10,0.9)',
      borderColor: `${accent}25`,
      borderLeft: `3px solid ${accent}`,
    }}>
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div>
          <div className="font-display text-lg leading-none" style={{ color: '#e8ff00', letterSpacing: '0.05em' }}>{signal.symbol}</div>
          <div className="text-[8px] mt-0.5" style={{ color: 'rgba(255,255,255,0.25)', fontFamily: 'monospace' }}>
            {signal.trend} · {signal.confidence}% confidence
          </div>
        </div>
        <div className="flex flex-col items-end gap-1">
          <div className="px-2.5 py-0.5 text-[10px] font-bold" style={{
            background: `${accent}15`, color: accent,
            border: `1px solid ${accent}30`,
            fontFamily: 'monospace',
          }}>
            {isLong ? '▲ LONG' : '▼ SHORT'}
          </div>
          <div className="text-[9px] font-bold" style={{ color: '#fff', fontFamily: 'monospace' }}>
            {fmt$(signal.price)}
          </div>
        </div>
      </div>

      {/* Signal levels */}
      <div className="grid grid-cols-2 gap-x-4 gap-y-1">
        {[
          { label: 'ENTRY',    value: fmt(signal.entry),    color: '#fff' },
          { label: 'R:R',      value: `${signal.rr || 2}:1`, color: '#a78bfa' },
          { label: 'STOP LOSS',value: fmt(signal.stopLoss), color: '#ff3366' },
          { label: 'TARGET 1', value: fmt(signal.target1),  color: '#00ffb3' },
          { label: 'CONF.',    value: `${signal.confidence}%`, color: '#e8ff00' },
          { label: 'TARGET 2', value: fmt(signal.target2),  color: '#00ffb3' },
        ].map(m => (
          <div key={m.label} className="flex justify-between text-[9px] py-0.5 border-b" style={{ borderColor: 'rgba(255,255,255,0.04)', fontFamily: 'monospace' }}>
            <span style={{ color: 'rgba(255,255,255,0.25)' }}>{m.label}</span>
            <span style={{ color: m.color, fontWeight: 700 }}>{m.value}</span>
          </div>
        ))}
      </div>

      {/* Confidence bar */}
      <div className="mt-3">
        <div className="h-1 w-full" style={{ background: 'rgba(255,255,255,0.05)' }}>
          <div className="h-full transition-all duration-700" style={{
            width: `${signal.confidence}%`,
            background: `linear-gradient(90deg, ${accent}80, ${accent})`,
          }} />
        </div>
      </div>
    </div>
  );
};

export default function SignalsPage() {
  const [activeGroup, setActiveGroup] = useState(0);
  const { data: signals, isLoading, isFetching } = useSignals(SIGNAL_GROUPS[activeGroup].syms);

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-end justify-between pb-4 border-b" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
        <div>
          <div className="text-[9px] tracking-[0.3em] uppercase mb-1" style={{ color: 'rgba(255,255,255,0.25)', fontFamily: 'monospace' }}>// AUTO-GENERATED SIGNALS</div>
          <div className="font-display text-4xl" style={{ color: '#00ffb3', letterSpacing: '0.05em', textShadow: '0 0 20px rgba(0,255,179,0.3)' }}>TRADING SIGNALS</div>
        </div>
        {isFetching && (
          <div className="flex items-center gap-2 mb-1">
            <div className="w-3 h-3 border border-t-acid rounded-full animate-spin" style={{ borderColor: 'rgba(232,255,0,0.15)', borderTopColor: '#e8ff00' }} />
            <div className="text-[9px]" style={{ color: 'rgba(255,255,255,0.2)', fontFamily: 'monospace' }}>UPDATING...</div>
          </div>
        )}
      </div>

      {/* Disclaimer */}
      <div className="px-4 py-2 border-l-2" style={{ borderColor: '#ff3366', background: 'rgba(255,51,102,0.04)' }}>
        <div className="text-[9px]" style={{ color: 'rgba(255,255,255,0.3)', fontFamily: 'monospace' }}>
          ⚠ These signals are generated by technical analysis algorithms. Not financial advice. Always do your own research and manage risk.
        </div>
      </div>

      {/* Market group tabs */}
      <div className="flex gap-1 flex-wrap">
        {SIGNAL_GROUPS.map((g, i) => (
          <button key={g.label} onClick={() => setActiveGroup(i)}
            className="px-4 py-2 text-[9px] font-bold tracking-widest border transition-all"
            style={{
              fontFamily: 'monospace',
              borderColor: activeGroup === i ? '#00ffb3' : 'rgba(255,255,255,0.08)',
              color:       activeGroup === i ? '#00ffb3' : 'rgba(255,255,255,0.3)',
              background:  activeGroup === i ? 'rgba(0,255,179,0.06)' : 'transparent',
            }}>{g.label}</button>
        ))}
      </div>

      {/* Signals grid */}
      {isLoading ? <Spinner /> : !signals?.length ? (
        <Empty message="No active signals for this group" icon="⊕" />
      ) : (
        <>
          <div className="flex items-center gap-3 mb-2">
            <div className="text-[9px]" style={{ color: 'rgba(255,255,255,0.2)', fontFamily: 'monospace' }}>
              {signals.filter(s => s.type === 'LONG').length} LONG · {signals.filter(s => s.type === 'SHORT').length} SHORT
            </div>
            <div className="flex gap-4">
              <div className="flex items-center gap-1.5">
                <div className="w-2 h-2" style={{ background: '#00ffb3' }} />
                <span className="text-[8px]" style={{ color: 'rgba(255,255,255,0.3)', fontFamily: 'monospace' }}>LONG</span>
              </div>
              <div className="flex items-center gap-1.5">
                <div className="w-2 h-2" style={{ background: '#ff3366' }} />
                <span className="text-[8px]" style={{ color: 'rgba(255,255,255,0.3)', fontFamily: 'monospace' }}>SHORT</span>
              </div>
            </div>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {signals.map(s => <SignalCard key={s.symbol} signal={s} />)}
          </div>
        </>
      )}

      {/* How signals are generated */}
      <Card>
        <CardLabel>SIGNAL GENERATION METHODOLOGY</CardLabel>
        <div className="grid md:grid-cols-3 gap-4 text-[9px]" style={{ fontFamily: 'monospace' }}>
          {[
            { step: '01', title: 'TREND DETECTION',     desc: 'EMA20/50/200 alignment + Supertrend direction determines primary bias' },
            { step: '02', title: 'MOMENTUM CONFIRM',    desc: 'RSI(14) + MACD histogram must confirm directional bias' },
            { step: '03', title: 'ENTRY CALCULATION',   desc: 'Entry at current price, SL = 1.5× ATR(14) from entry' },
            { step: '04', title: 'TARGET PROJECTION',   desc: 'T1 = 2× risk, T2 = 3× risk from entry point' },
            { step: '05', title: 'CONFIDENCE SCORE',    desc: '6-factor scoring: EMA stack, RSI, MACD, volume, Supertrend, structure' },
            { step: '06', title: 'FILTER & PUBLISH',    desc: 'Only LONG/SHORT signals published — NEUTRAL excluded' },
          ].map(m => (
            <div key={m.step} className="space-y-1">
              <div className="font-black" style={{ color: '#e8ff00' }}>STEP {m.step} — {m.title}</div>
              <div style={{ color: 'rgba(255,255,255,0.35)' }}>{m.desc}</div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
